export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';
export const QUESTIONS_FETCHING = 'QUESTIONS_FETCHING';
export const QUESTIONS_RECEIVED = 'QUESTIONS_RECEIVED';
export const RECORD_ANSWER = 'RECORD_ANSWER';
export const UPDATE_RESULTS = 'UPDATE_RESULTS';